print 'merging job.WorkItemStatusType';
go
set transaction isolation level serializable;
go
set nocount on;
go
merge job.WorkItemStatusType as dest
using 
(
    values
    (1, 'Queued', SYSUTCDATETIME()),
    (2, 'Started', SYSUTCDATETIME()),
    (3, 'ReStarted', SYSUTCDATETIME()),
    (4, 'Completed', SYSUTCDATETIME())
) as src(id, enumeration, inserttimestamp)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    on 1=1 and dest.id = src.id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
when matched and (dest.id <> src.id or dest.enumeration <> src.enumeration or dest.inserttimestamp <> src.inserttimestamp)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    then 
        update 
            set dest.id = src.id, dest.enumeration = src.enumeration, dest.inserttimestamp = src.inserttimestamp
when not matched by target 
    then                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        insert(id, enumeration, inserttimestamp)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        values(src.id, src.enumeration, src.inserttimestamp);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
go
print 'job.WorkItemStatusType rows merged: ' + cast(@@rowcount as varchar(100));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
go